// export const LEFT_FORM_CENTRE_X = -3.5
// export const RIGHT_FORM_CENTRE_X = -LEFT_FORM_CENTRE_X
// export const PROJECTOR_CENTRE_Y = 1
// export const SCREEN_IMAGE_CENTRE_Y = 2.6
// export const SCREEN_IMAGE_RADIUS_X = 2.8
// export const SCREEN_IMAGE_RADIUS_Y = 2
// export const MEMBRANE_LENGTH = 15
export const PI = Math.PI
export const TWO_PI = PI * 2
export const HALF_PI = PI / 2
export const QUARTER_PI = PI / 4
